// <auto-generated />
using System;
using Finanzas.Data.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finanzas.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260702015735_AgregaTiposGastosSeed")]
    partial class AgregaTiposGastosSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Finanzas.Domain.Models.Gastos", b =>
                {
                    b.Property<int>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.Property<int?>("TipoGastoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GastoId");

                    b.HasIndex("TipoGastoId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Finanzas.Domain.Models.TipoGastos", b =>
                {
                    b.Property<int>("TipoGastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TipoGastoId");

                    b.ToTable("TiposGastos");

                    b.HasData(
                        new
                        {
                            TipoGastoId = 1,
                            Descripcion = "Alimentos"
                        },
                        new
                        {
                            TipoGastoId = 2,
                            Descripcion = "Transporte"
                        },
                        new
                        {
                            TipoGastoId = 3,
                            Descripcion = "Servicios"
                        },
                        new
                        {
                            TipoGastoId = 4,
                            Descripcion = "Ocio"
                        },
                        new
                        {
                            TipoGastoId = 5,
                            Descripcion = "Salud"
                        });
                });

            modelBuilder.Entity("Finanzas.Domain.Models.Gastos", b =>
                {
                    b.HasOne("Finanzas.Domain.Models.TipoGastos", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("TipoGastoId");

                    b.Navigation("TipoGasto");
                });
#pragma warning restore 612, 618
        }
    }
}
