// <auto-generated />
using System;
using Finanzas.Data.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finanzas.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finanzas.Domain.Models.Gastos", b =>
                {
                    b.Property<int>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GastoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MetodoPagoId")
                        .HasColumnType("integer");

                    b.Property<double>("Monto")
                        .HasColumnType("double precision");

                    b.Property<int?>("TipoGastoId")
                        .HasColumnType("integer");

                    b.HasKey("GastoId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("TipoGastoId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Finanzas.Domain.Models.MetodoPagos", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetodoPagoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MetodoPagoId");

                    b.ToTable("MetodosPago");

                    b.HasData(
                        new
                        {
                            MetodoPagoId = 1,
                            Descripcion = "Efectivo"
                        },
                        new
                        {
                            MetodoPagoId = 2,
                            Descripcion = "Tarjeta de crédito"
                        },
                        new
                        {
                            MetodoPagoId = 3,
                            Descripcion = "Tarjeta de débito"
                        },
                        new
                        {
                            MetodoPagoId = 4,
                            Descripcion = "Transferencia bancaria"
                        },
                        new
                        {
                            MetodoPagoId = 7,
                            Descripcion = "Otro"
                        });
                });

            modelBuilder.Entity("Finanzas.Domain.Models.Prestamos", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrestamoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Monto")
                        .HasColumnType("double precision");

                    b.HasKey("PrestamoId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("Finanzas.Domain.Models.TipoGastos", b =>
                {
                    b.Property<int>("TipoGastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoGastoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoGastoId");

                    b.ToTable("TiposGastos");

                    b.HasData(
                        new
                        {
                            TipoGastoId = 1,
                            Descripcion = "Alimentos"
                        },
                        new
                        {
                            TipoGastoId = 2,
                            Descripcion = "Transporte"
                        },
                        new
                        {
                            TipoGastoId = 3,
                            Descripcion = "Servicios"
                        },
                        new
                        {
                            TipoGastoId = 4,
                            Descripcion = "Ocio"
                        },
                        new
                        {
                            TipoGastoId = 5,
                            Descripcion = "Salud"
                        },
                        new
                        {
                            TipoGastoId = 6,
                            Descripcion = "Gasolina"
                        },
                        new
                        {
                            TipoGastoId = 7,
                            Descripcion = "Subscripciones"
                        },
                        new
                        {
                            TipoGastoId = 8,
                            Descripcion = "Supermercado"
                        });
                });

            modelBuilder.Entity("Finanzas.Domain.Models.Gastos", b =>
                {
                    b.HasOne("Finanzas.Domain.Models.MetodoPagos", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId");

                    b.HasOne("Finanzas.Domain.Models.TipoGastos", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("TipoGastoId");

                    b.Navigation("MetodoPago");

                    b.Navigation("TipoGasto");
                });
#pragma warning restore 612, 618
        }
    }
}
